### ISSUE TITLE
Corrupted Enigma error after fresh install

### ISSUE THREAD

**Issue by Hughtech** [enigma-dev/enigma-dev#1134]
I started to re-install ENIGMA on one of my LINUX machines when I encountered various errors. Not a really big issue since I was testing an Update to my previous OS. however I was concerned when I received several messages stating that the IDE was corrupt when I tried to run LateralGM.

![screenshot from 2018-01-06 15-47-10](https://user-images.githubusercontent.com/19632613/34654306-58335e40-f3d0-11e7-8499-1d8468eda154.png)

This happened at every fresh install using 3 separate LINUX OS; Ubuntu, MINT and MX LINUX 17. I had to re-install my old MX LINUX 16.1 and copy LateralGM from a previous backup in order to get it up and running. 
I had tried to use Version 1.8.10 before but JAVA crashed, so I then returned back to version 1.8.7. 

It was suggested that I place this also here.

**Comment by RobertBColton** [comment]
This is a continuation from: https://github.com/IsmAvatar/LateralGM/issues/335

@Hughtech can you please clarify how you went about: "re-install ENIGMA"

Did you run the install.py script to update LGM jars? My thoughts are that one of our setup scripts failed during the download and just corrupted the jar file.

**Comment by Hughtech** [comment]
I've done what you've asked in the form of creating a video of the steps I took. It show a fresh install of Ubuntu 16 GNOME in a Virtual-box environment. It pretty much explains it all.
https://youtu.be/F_vW37ZB42M

**Comment by RobertBColton** [comment]
I'm getting the following error message, can you please check to see if the video is public?

![YouTube Error](https://user-images.githubusercontent.com/3212801/34663598-8df2932a-f425-11e7-9c5a-5237ec5b33a6.png)

**Comment by Hughtech** [comment]
Checked. It was indeed set as 'Private'. Apologies. Should be working now.
https://youtu.be/F_vW37ZB42M

**Comment by RobertBColton** [comment]
Ok, I see now. I still basically have the same idea, I believe somehow lateralgm.jar was corrupted by the setup script and now install.py refuses to overwrite it. So try this, go into enigma-dev/ and delete lateralgm.jar and run the install.py script again. If it still complains I'll update the MD5 hash online. I want to update it anyway to grab the new version, but I want to wait and see if it could be the cause of the problem. So please let me know how deleting lateralgm.jar goes first.

**Comment by Hughtech** [comment]
did as you suggested and got this. Was indeed an error on MD5

![lateralgm_error_from_phyton_script](https://user-images.githubusercontent.com/19632613/34669526-7033bbb6-f448-11e7-93d6-6a48530d0a60.png)

**Comment by RobertBColton** [comment]
So launching ENIGMA works now? LateralGM will open?

**Comment by Hughtech** [comment]
Another error came up stating that it can't access LateralGm. I agree that the installation has errors.  According to the readout, the hash file doesn't match, so it needs to be updated.

![lateralgm_error_from_phyton_script2](https://user-images.githubusercontent.com/19632613/34669798-e259f632-f449-11e7-9cdc-7fdd2d9222b2.png)

**Comment by RobertBColton** [comment]
Oh I'm sorry, I now realize what is going on. I made a new release for LGM, and I forgot to update the actual URL when I changed the filename to include the version number.

Fixed: https://github.com/enigma-dev/ExtraPackages/commit/9b67c751aa4c31fa8fc513c9f92414ea701b2a82

Please give it one more try and it should be good now. Please let me know so I can close this.

**Comment by Hughtech** [comment]
LateralGm hash is updated. However Infolist and some others also need to updated. Still getting the error.
![lateralgm_error_from_phyton_script3](https://user-images.githubusercontent.com/19632613/34670126-60cae660-f44b-11e7-80b3-f231dfadc104.png)

**Comment by RobertBColton** [comment]
No those do not need updated, you should be fine without them. We are aware of that issue already (https://github.com/enigma-dev/ExtraPackages/issues/4), the person who maintains them is not reachable. We want to replace this with a different installation mechanism.

Can you confirm if ENIGMA launches now?

**Comment by Hughtech** [comment]
It still says that it can't access lateralgm.jar.

**Comment by RobertBColton** [comment]
Oh sorry, try deleting lateralgm.jar again, running install.py, and then give ENIGMA one more go.

**Comment by RobertBColton** [comment]
I'm not familiar with this start.sh script, but I see it was contributed to the Wiki by a user:
https://enigma-dev.org/docs/Wiki/Install:Linux
It looks like it runs lateralgm.jar from this pastebin:
http://pastebin.com/raw/6ZmrzWKP

You can also try just cd'ing into enigma-dev/ and then running "java -jar lateralgm.jar" as that's what I do on Linux. I've never used the setup script myself before, not that there's anything wrong with it.

**Comment by fundies** [comment]
run md5sum on lateralgm.jar
[greg@archlinux enigma-dev]$ md5sum lateralgm.jar 
c58866c40bfbaec33e4abc307cd3eab7  lateralgm.jar

**Comment by RobertBColton** [comment]
@fundies He's beyond that now, he's getting "unable to access jarfile".

**Comment by fundies** [comment]
I want to confirm he has the correct jar

**Comment by Hughtech** [comment]
what i'm doing now is to delete the entire enigma-dev folder and start from scratch again. 

Success! :) :) LateralGM have indeed loaded with the updated version. Don't worry about the JAVA error on the pic......it had installation errors to begin with but the issue with LateralGM being corrupted now seems to solved. 

Thanks Robert for your assist.
I'm going to try it out with an OS i know that it works with and hopefully no more errors. :) (We can only hope:)

![lateralgm_error_from_phyton_script_success](https://user-images.githubusercontent.com/19632613/34670978-e21c9fda-f44e-11e7-8ca1-412acdcafef7.png)

**Comment by RobertBColton** [comment]
Absolutely, glad you got it working, please let us know if you have any other issues!
